## Tratamento dos Dados

### Entendimento Inicial

#### Importanto dados e bibliotecas

In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/glp-2023-01.csv", delimiter=";")
df.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,CO,MS,CAMPO GRANDE,COMPANHIA ULTRAGAZ S A,61.602.199/0024-09,RUA AMARO CASTRO LIMA,1852,NaN,VILA NOVA CAMPO GRANDE,79106-361,GLP,05/01/2023,120,NaN,R$ / 13 kg,ULTRAGAZ
1,CO,MS,CAMPO GRANDE,SUPERGASBRAS ENERGIA LTDA,19.791.896/0086-91,RUA NILO JAVARI BAREM,841,NaN,VILA ELIANE,79103-280,GLP,05/01/2023,120,NaN,R$ / 13 kg,SUPERGASBRAS ENERGIA
2,S,RS,PELOTAS,SUPERGASBRAS ENERGIA LTDA,19.791.896/0020-65,AVENIDA PRESIDENTE JOÃO BELCHIOR GOULART,7565,NaN,FRAGATA,96040-000,GLP,03/01/2023,108,NaN,R$ / 13 kg,SUPERGASBRAS ENERGIA
3,SE,MG,MONTES CLAROS,SUPERGASBRAS ENERGIA LTDA,19.791.896/0070-24,AVENIDA DEP. PLINIO RIBEIRO,3220,NaN,JARDIM PALMEIRAS,39402-194,GLP,05/01/2023,120,NaN,R$ / 13 kg,SUPERGASBRAS ENERGIA
4,NE,CE,JUAZEIRO DO NORTE,COMERCIO DE PETROLEO COLORADO LTDA,00.198.451/0001-85,RUA DOMINGOS CALAZANS,518,NaN,TRIANGULO,63041-130,GLP,05/01/2023,109,NaN,R$ / 13 kg,NACIONAL GÁS BUTANO

#### Obtendo uma visão geral da composição do dataset

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 105341 entries, 0 to 105340
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     105341 non-null  str
 1   Estado - Sigla     105341 non-null  str
 2   Municipio          105341 non-null  str
 3   Revenda            105341 non-null  str
 4   CNPJ da Revenda    105341 non-null  str
 5   Nome da Rua        105341 non-null  str
 6   Numero Rua         105341 non-null  str
 7   Complemento        26414 non-null   str
 8   Bairro             105323 non-null  str
 9   Cep                105341 non-null  str
 10  Produto            105341 non-null  str
 11  Data da Coleta     105341 non-null  str
 12  Valor de Venda     105341 non-null  str
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  105341 non-null  str
 15  Bandeira           105341 non-null  str
dtypes: float64(1), str(15)
memory usage: 28.0 MB

#### Removendo coluna totalmente composta de valores nulos

In [3]:
df = df.drop(columns=['Valor de Compra'])
df.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira
0,CO,MS,CAMPO GRANDE,COMPANHIA ULTRAGAZ S A,61.602.199/0024-09,RUA AMARO CASTRO LIMA,1852,NaN,VILA NOVA CAMPO GRANDE,79106-361,GLP,05/01/2023,120,R$ / 13 kg,ULTRAGAZ
1,CO,MS,CAMPO GRANDE,SUPERGASBRAS ENERGIA LTDA,19.791.896/0086-91,RUA NILO JAVARI BAREM,841,NaN,VILA ELIANE,79103-280,GLP,05/01/2023,120,R$ / 13 kg,SUPERGASBRAS ENERGIA
2,S,RS,PELOTAS,SUPERGASBRAS ENERGIA LTDA,19.791.896/0020-65,AVENIDA PRESIDENTE JOÃO BELCHIOR GOULART,7565,NaN,FRAGATA,96040-000,GLP,03/01/2023,108,R$ / 13 kg,SUPERGASBRAS ENERGIA
3,SE,MG,MONTES CLAROS,SUPERGASBRAS ENERGIA LTDA,19.791.896/0070-24,AVENIDA DEP. PLINIO RIBEIRO,3220,NaN,JARDIM PALMEIRAS,39402-194,GLP,05/01/2023,120,R$ / 13 kg,SUPERGASBRAS ENERGIA
4,NE,CE,JUAZEIRO DO NORTE,COMERCIO DE PETROLEO COLORADO LTDA,00.198.451/0001-85,RUA DOMINGOS CALAZANS,518,NaN,TRIANGULO,63041-130,GLP,05/01/2023,109,R$ / 13 kg,NACIONAL GÁS BUTANO

#### Atribuindo Tipos corretos onde necessário

In [4]:
df['Valor de Venda'] = df['Valor de Venda'].str.replace(',', '.')
df['Valor de Venda'] = df['Valor de Venda'].astype(float)

df['Data da Coleta'] = pd.to_datetime(df['Data da Coleta'], dayfirst=True)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 105341 entries, 0 to 105340
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     105341 non-null  str
 1   Estado - Sigla     105341 non-null  str
 2   Municipio          105341 non-null  str
 3   Revenda            105341 non-null  str
 4   CNPJ da Revenda    105341 non-null  str
 5   Nome da Rua        105341 non-null  str
 6   Numero Rua         105341 non-null  str
 7   Complemento        26414 non-null   str
 8   Bairro             105323 non-null  str
 9   Cep                105341 non-null  str
 10  Produto            105341 non-null  str
 11  Data da Coleta     105341 non-null  datetime64[us]
 12  Valor de Venda     105341 non-null  float64
 13  Unidade de Medida  105341 non-null  str
 14  Bandeira           105341 non-null  str
dtypes: datetime64[us](1), float64(1), str(13)
memory usage: 25.8 MB

### Aplicando a mesma lógica para o restante dos datasets

### Importando datasets

In [6]:
df1 = pd.read_csv('../data/raw/glp-2023-02.csv', delimiter=';')
df2 = pd.read_csv('../data/raw/glp-2024-01.csv', delimiter=';')
df3 = pd.read_csv('../data/raw/glp-2024-02.csv', delimiter=';')
df4 = pd.read_csv('../data/raw/glp-2025-01.csv', delimiter=';')
df5 = pd.read_csv('../data/raw/glp-2025-02.csv', delimiter=';')

### Tratando erros e valores faltantes

In [7]:
def drop_coluna(dframe):
    dframe = dframe.drop(columns=['Valor de Compra'])
    return dframe


df1 = drop_coluna(df1)
df2 = drop_coluna(df2)
df3 = drop_coluna(df3)
df4 = drop_coluna(df4)
df5 = drop_coluna(df5)

In [8]:
df2.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira
0,S,SC,JARAGUA DO SUL,POSTO CIDADE LTDA,81.352.882/0002-37,RUA PADRE ALBERTO ROMUALD JACOBS,404,NaN,VILA LENZI,89252-280,GLP,01/01/2024,"99,9",R$ / 13 kg,NACIONAL GÁS BUTANO
1,SE,SP,JACAREI,AUTO POSTO BARAO DE JACAREI LTDA,96.265.921/0001-55,RUA BARAO DE JACAREI,1396,NaN,CENTRO,12308-000,GLP,01/01/2024,"99,9",R$ / 13 kg,LIQUIGÁS
2,SE,SP,JACAREI,POSTO DE SERVICOS SHOPPING DE JACAREI LTDA,62.122.908/0001-25,AVENIDA SIQUEIRA CAMPOS,1199,NaN,VILA PINHEIRO,12307-000,GLP,01/01/2024,"99,9",R$ / 13 kg,BRANCA
3,SE,SP,JACAREI,AUTO POSTO R N M LTDA,59.790.436/0001-74,RODOVIA NILO MAXIMO,3550,KM 4,SANTO ANTONIO DA BOA VISTA,12315-010,GLP,01/01/2024,89,R$ / 13 kg,SUPERGASBRAS ENERGIA
4,SE,SP,PRAIA GRANDE,AUTO POSTO DELTA MAR LTDA,02.273.616/0001-61,AVENIDA PRESIDENTE KENNEDY,7678,ANEXO AUTO POSTO,OCIAN,11704-100,GLP,01/01/2024,108,R$ / 13 kg,ULTRAGAZ

In [9]:
def type_change(dframe):
    dframe['Valor de Venda'] = dframe['Valor de Venda'].astype(str)
    dframe['Valor de Venda'] = dframe['Valor de Venda'].str.replace(',', '.')
    dframe['Valor de Venda'] = dframe['Valor de Venda'].astype(float)
    dframe['Data da Coleta'] = pd.to_datetime(dframe['Data da Coleta'], dayfirst=True)
    return dframe

def convert_to_string_columns(dframe, exclude_cols=['Data da Coleta', 'Valor de Venda']):
    for col in dframe.columns:
        if col not in exclude_cols:
            dframe[col] = dframe[col].astype(pd.StringDtype())
    return dframe

frames = [df,df1,df2,df3,df4,df5]

for i, dframe in enumerate(frames):
    dframe = type_change(dframe)
    dframe = convert_to_string_columns(dframe)
    frames[i] = dframe

In [10]:
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 71780 entries, 0 to 71779
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Regiao - Sigla     71780 non-null  string
 1   Estado - Sigla     71780 non-null  string
 2   Municipio          71780 non-null  string
 3   Revenda            71780 non-null  string
 4   CNPJ da Revenda    71780 non-null  string
 5   Nome da Rua        71780 non-null  string
 6   Numero Rua         71780 non-null  string
 7   Complemento        18684 non-null  string
 8   Bairro             71780 non-null  string
 9   Cep                71780 non-null  string
 10  Produto            71780 non-null  string
 11  Data da Coleta     71780 non-null  datetime64[us]
 12  Valor de Venda     71780 non-null  float64
 13  Unidade de Medida  71780 non-null  string
 14  Bandeira           71780 non-null  string
dtypes: datetime64[us](1), float64(1), string(13)
memory usage: 17.6 MB

### Salvando datasets no formato .parquet

In [11]:
df.to_parquet('../data/processed/glp-2023-01-processed.parquet')
df1.to_parquet('../data/processed/glp-2023-02-processed.parquet')
df2.to_parquet('../data/processed/glp-2024-01-processed.parquet')
df3.to_parquet('../data/processed/glp-2024-02-processed.parquet')
df4.to_parquet('../data/processed/glp-2025-01-processed.parquet')
df5.to_parquet('../data/processed/glp-2025-02-processed.parquet')

In [12]:
teste = pd.read_parquet('../data/processed/glp-2025-02-processed.parquet')
teste.info()

<class 'pandas.DataFrame'>
RangeIndex: 53423 entries, 0 to 53422
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Regiao - Sigla     53423 non-null  string
 1   Estado - Sigla     53423 non-null  string
 2   Municipio          53423 non-null  string
 3   Revenda            53423 non-null  string
 4   CNPJ da Revenda    53423 non-null  string
 5   Nome da Rua        53423 non-null  string
 6   Numero Rua         53423 non-null  string
 7   Complemento        14220 non-null  string
 8   Bairro             53423 non-null  string
 9   Cep                53423 non-null  string
 10  Produto            53423 non-null  string
 11  Data da Coleta     53423 non-null  datetime64[us]
 12  Valor de Venda     53423 non-null  float64
 13  Unidade de Medida  53423 non-null  string
 14  Bandeira           53423 non-null  string
dtypes: datetime64[us](1), float64(1), string(13)
memory usage: 12.8 MB